{ "providers" : [{
	"id": "f01",
	"image": "GroupImages/Fitness/fitnessProviders/Nash_sm.jpg",
	"title": "Nash",
	"JobDesc": "Fitness Coach",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "Nash is a certified nutritionist with 5 years of experience. She has worked with numerous clients on issues like weight loss, family meal planning and nutrition for different ages.",
	"Location": "NewMarket, ON",
	"pageLink": "Low_Impact_Cardio"
},
{
	"id": "f02",
	"image": "GroupImages/Fitness/fitnessProviders/Evan.jpg",
	"title": "Evan",
	"JobDesc": "Interval Trainer",
	"Rates": "$40/hr",
	"Ratings": 5,
	"shortDesc": "Evan is a Cardio Trainer with 12 years of experience. His specialization is Interval training that helps to keep his clients in top shape. Evan is also a yoga enthusiast with a specialization in Hatha Yoga.",
	"Location": "Toronto, ON",
	"pageLink": "Interval_Training_for_Beginners"
},
{
	"id": "f03",
	"image": "GroupImages/Fitness/fitnessProviders/Jeremy_sm.jpg",
	"title": "Jeremy",
	"JobDesc": "Trainer",
	"Rates": "$55/hr",
	"Ratings": 4,
	"shortDesc": "Jeremy is a fitness trainer since the year 2000 and has helped his clients with their weight loss, muscle gain, and sports performance goals. ",
	"Location": "Santa Clara, CA",
	"pageLink": "Mixed_Interval_30"
},
{
	"id": "f04",
	"image": "GroupImages/Fitness/fitnessProviders/Matt_sm.jpg",
	"title": "Matt",
	"JobDesc": "Cardio Trainer",
	"Rates": "$30/hr",
	"Ratings": 5,
	"shortDesc": "Matt is a trainer with 5 years of experience. He offers customized meal plans, training sessions, and lifestyle maintance programs.",
	"Location": "San Bruno, CA",
	"pageLink": "Mixed_Interval_30"
},
{
	"id": "f05",
	"image": "GroupImages/Fitness/fitnessProviders/Josh.jpg",
	"title": "Josh",
	"JobDesc": "Personal Trainer",
	"Rates": "$65/hr",
	"Ratings": 4,
	"shortDesc": "Josh has worked with a variety of clients as a personal trainer.  Over the past 3 years he has helped his clients in aerobic, cicuit and strength training.",
	"Location": "Bowling Green, OH",
	"pageLink": "Cardio_Basics"
},
{
	"id": "f06",
	"image": "GroupImages/Fitness/fitnessProviders/Natasha_sm.jpg",
	"title": "Natasha",
	"JobDesc": "Yoga Trainer",
	"Rates": "$30/hr",
	"Ratings": 2,
	"shortDesc": "Natasha is a seasoned personal Trainer. Her portfolio ranges from pre and post natal clients, athletes, weight losers and 10 years of experience a group exercise instructor.",
	"Location": "Logan, UT",
	"pageLink": "Mixed_Interval_30"
},
{
	"id": "f07",
	"image": "GroupImages/Fitness/fitnessProviders/Nate.jpg",
	"title": "Nate",
	"JobDesc": "Cardio Trainer",
	"Rates": "$45/hr",
	"Ratings": 4,
	"shortDesc": "Nate has more than 5 years of experience as a cardio trainer. He focuses on edurance or aerobic training for heart health and strength training for muscle building. ",
	"Location": "Miami, FL",
	"pageLink": "Cardio_for_Weight_Loss"
},
{
	"id": "f08",
	"image": "GroupImages/Fitness/fitnessProviders/Lily.jpg",
	"title": "Lily",
	"JobDesc": "Yoga Trainer",
	"Rates": "$30/hr",
	"Ratings": 3,
	"shortDesc": "Lily is a trained yoga professional that uses yoga for maintaining healthy health and weight loss.",
	"Location": "Cupertino, CA",
	"pageLink": "Cardio_for_Weight_Loss"
},
{
	"id": "f09",
	"image": "GroupImages/Fitness/fitnessProviders/Tim.jpg",
	"title": "Tim",
	"JobDesc": "Health Coach",
	"Rates": "$55/hr",
	"Ratings": 3,
	"shortDesc": "Tim is a high energy coach that keeps his clients motivated with new fitness techniques and ideas. He specializes in sculpting, core training, and kickboxing.",
	"Location": "Houston, TX",
	"pageLink": "Burn_Fat"
},
{
	"id": "f10",
	"image": "GroupImages/Fitness/fitnessProviders/Steven.jpg",
	"title": "Steven",
	"JobDesc": "Trainer",
	"Rates": "$30/hr",
	"Ratings": 2,
	"shortDesc": "Steven helps young professionals and executives create systems to accelerate their weight loss goals. He develops individualized weight loss programs based on client needs.",
	"Location": "NewMarket, ON",
	"pageLink": "Interval_Training_for_Beginners"
},
{
	"id": "f11",
	"image": "GroupImages/Fitness/fitnessProviders/Roxanne.jpg",
	"title": "Roxanne",
	"JobDesc": "Trainer",
	"Rates": "$50/hr",
	"Ratings": 5,
	"shortDesc": "Being an active and athletic person all her life, choosing a career as a fitness trainer was easy for Roxanne. She works with clients of all ages, developing personalized sessions and delivering them.",
	"Location": "Pleasanton, CA",
	"pageLink": "At_Home_Cardio"
},
{
	"id": "f12",
	"image": "GroupImages/Fitness/fitnessProviders/Rob.jpg",
	"title": "Rob",
	"JobDesc": "Trainer",
	"Rates": "$40/hr",
	"Ratings": 3,
	"shortDesc": "Rob believes taht for the body to work optimally, it must be in  balance. Following this approach, Rob focuses on cadrio, strengthening, flexibility, core and balancing exercises.",
	"Location": "Logan, UT",
	"pageLink": "At_Home_Cardio"
},
{
	"id": "f13",
	"image": "GroupImages/Fitness/fitnessProviders/Rayaan.jpg",
	"title": "Rayaan",
	"JobDesc": "Cardio Expert",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "Rayaan has an extensive training in Stott Pilates, Matwork and equipment, kettlebell and kickboxing. She has worked with rehab clients and believes in a wholistic approach towards wellbeing.",
	"Location": "Houston, TX",
	"pageLink": "At_Home_Cardio"
},
{
	"id": "f14",
	"image": "GroupImages/Fitness/fitnessProviders/Olivia.jpg",
	"title": "Olivia",
	"JobDesc": "Health Coach",
	"Rates": "$70/hr",
	"Ratings": 4,
	"shortDesc": "Olivia specializes in one-on-one coaching, focusing on personal goal setting. She has 7 years of experience as a health coach with experience in HIIT, cardio training, weight loss and core training. ",
	"Location": "San Mateo, CA",
	"pageLink": "HIIT"
},
{
	"id": "f15",
	"image": "GroupImages/Fitness/fitnessProviders/Catherine_sm.jpg",
	"title": "Catherine",
	"JobDesc": "Yoga Trainer",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "Catherine is a certified fitness instructor with 8 years of experiences. She speicalizes in sports related injuries, rebahbilitation programs and post stroke and joint replacement rehab.",
	"Location": "NewMarket, ON",
	"pageLink": "Mixed_Interval_30"
},
{
	"id": "f16",
	"image": "GroupImages/Fitness/fitnessProviders/Lex_sm.jpg",
	"title": "Lex",
	"JobDesc": "Fitness Expert",
	"Rates": "$30/hr",
	"Ratings": 3,
	"shortDesc": "Lex is a fitness expert with over 8 years of experience. He is a friendly and dedicated personal trainer who helps people with their health and fitness goals.",
	"Location": "Houston, TX",
	"pageLink": "Mixed_Interval_30"
},
{
	"id": "f17",
	"image": "GroupImages/Fitness/fitnessProviders/Julio.jpg",
	"title": "Julio",
	"JobDesc": "Health Coach",
	"Rates": "$30/hr",
	"Ratings": 3,
	"shortDesc": "Juilio believes in making people the masters of their own health. He coaches clients about their strengths and has 10-plus years of experience in endurance sports.",
	"Location": "Cupertino, CA",
	"pageLink": "HIIT"
},
{
	"id": "f18",
	"image": "GroupImages/Fitness/fitnessProviders/Tom_sm.jpg",
	"title": "Tom",
	"JobDesc": "Trainer",
	"Rates": "$50/hr",
	"Ratings": 3,
	"shortDesc": "Tom has worked as a fitness trainer for 15 years and motivates his clients providing coaching and knowledge to achieve their goals. ",
	"Location": "Houston, TX",
	"pageLink": "HIIT"
},
{
	"id": "f19",
	"image": "GroupImages/Fitness/fitnessProviders/Jackie_sm.jpg",
	"title": "Jackie",
	"JobDesc": "Health Trainer",
	"Rates": "$45/hr",
	"Ratings": 4,
	"shortDesc": "Jackie has a real passion for fitness and an understanding for life changing effects of a successful exercise and nutritional program. Train with Jackie to achieve all your health and wellness goals.",
	"Location": "NewMarket, ON",
	"pageLink": "High_Intensity_Aerobics"
},
{
	"id": "f20",
	"image": "GroupImages/Fitness/fitnessProviders/Naomi.jpg",
	"title": "Naomi",
	"JobDesc": "Health Coach",
	"Rates": "$30/hr",
	"Ratings": 2,
	"shortDesc": "Naomi has trained with multiple level clients, from beginners to athletes. She enjoys building a personal rapport with her clients and working at a pace that suits her clients.",
	"Location": "Cupertino, CA",
	"pageLink": "High_Intensity_Aerobics"
},
{
	"id": "f21",
	"image": "GroupImages/Fitness/fitnessProviders/JoAnn.jpg",
	"title": "JoAnn",
	"JobDesc": "Health Coach",
	"Rates": "$60/hr",
	"Ratings": 4,
	"shortDesc": "JoAnn is a certified ACE personal trainer. She specializes in pre and post natal care, weight loss, injury rehabilitation, and muscle toning.",
	"Location": "Logan, UT",
	"pageLink": "Cardio_Basics"
},
{
	"id": "f22",
	"image": "GroupImages/Fitness/fitnessProviders/Jesse.jpg",
	"title": "Jesse",
	"JobDesc": "Trainer",
	"Rates": "$35/hr",
	"Ratings": 3,
	"shortDesc": "Jesse is a certified personal trainer who has spent last 15 years learning about the importance of fitness and training. He is a dedicated weight trainer who helps clients attain healthy body weight.",
	"Location": "Pleasanton, CA",
	"pageLink": "Low_Impact_Cardio"
},
{
	"id": "f23",
	"image": "GroupImages/Fitness/fitnessProviders/Dahphne.jpg",
	"title": "Dahphne",
	"JobDesc": "Fitness Expert",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "Dahpne believes that true fitness is a holistic model and offers training in muscle toning, weight management and personal wellness.",
	"Location": "Pleasanton, CA",
	"pageLink": "Low_Impact_Cardio"
},
{
	"id": "f24",
	"image": "GroupImages/Wellness/Providers/Trisha.jpg",
	"title": "Trisha",
	"JobDesc": "Yoga Trainer",
	"Rates": "$50/hr",
	"Ratings": 1,
	"shortDesc": "Trisha is a certified Jivamukti yoga teacher. Her classes focus on alignment, building strength and increasing flexibility.",
	"Location": "Cupertino, CA",
	"pageLink": "Outdoor_Workouts"
}]

}