[{
	"id": "p01",
	"image": "GroupImages/Wellness/Providers/Alexia.jpg",
	"title": "Alexia",
	"JobDesc": "Nutritionist",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "Alexia is a certified nutritionist with 5 years of experience. She has worked with numerous clients on issues like weight loss, family meal planning and nutrition for different ages.",
	"Location": "NewMarket, ON",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p02",
	"image": "GroupImages/Wellness/Providers/Casey.jpg",
	"title": "Casey",
	"JobDesc": "Yoga Trainer",
	"Rates": "$40/hr",
	"Ratings": 5,
	"shortDesc": "Casey is a Yoga Trainer with 12 years of experience. Her specialization is Hath Yoga that helps to remedy back problems, anxiety and mental tension.",
	"Location": "Toronto, ON",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p03",
	"image": "GroupImages/Wellness/Providers/Evan.jpg",
	"title": "Evan",
	"JobDesc": "Dietitian",
	"Rates": "$55/hr",
	"Ratings": 4,
	"shortDesc": "Evan is a registered dietitian. He has worked with low-income families, and on issues like childhood obesity and medical conditions like heart attacks, osteoporosis and cancer.",
	"Location": "Santa Clara, CA",
	"page": "www.google.com",
	"DetoxDiet": "N"
},
{
	"id": "p04",
	"image": "GroupImages/Wellness/Providers/Jesse.jpg",
	"title": "Jesse",
	"JobDesc": "Dietitian",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "Jessie is a clinical dietitian with a focus on obseity, weight loss and weight management. He has dealt with clients with digestive disorders, GI and irrtable bowel syndrome.",
	"Location": "San Bruno, CA",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p05",
	"image": "GroupImages/Wellness/Providers/Jillian.jpg",
	"title": "Jillian",
	"JobDesc": "Dietitian",
	"Rates": "$65/hr",
	"Ratings": 4,
	"shortDesc": "Jillian is a registered dietitan that focuses on food safety. She has 3 years of experience working with underweight clients, teaching them through cooking and food demonstrations.",
	"Location": "Bowling Green, OH",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p06",
	"image": "GroupImages/Wellness/Providers/JoAnn.jpg",
	"title": "JoAnn",
	"JobDesc": "Yoga Trainer",
	"Rates": "$30/hr",
	"Ratings": 2,
	"shortDesc": "Joann started became a yoga practitioner in 2002 and has gained excellence in AShtanga yoga. She focuses on building deep core muscles through vigorous training.",
	"Location": "Logan, UT",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p07",
	"image": "GroupImages/Wellness/Providers/Joleen.jpg",
	"title": "Joleen",
	"JobDesc": "Nutritionist",
	"Rates": "$45/hr",
	"Ratings": 4,
	"shortDesc": "Joleen has worked as a nutritionist for 15 years and focuses on vegetarian, vegan or raw eating. She specializes in dealing with food allergies and intolerance.",
	"Location": "Miami, FL",
	"page": "www.google.com",
	"DetoxDiet": "N"
},
{
	"id": "p08",
	"image": "GroupImages/Wellness/Providers/Joe.jpg",
	"title": "Joseph",
	"JobDesc": "Dietitian",
	"Rates": "$30/hr",
	"Ratings": 3,
	"shortDesc": "Joseph has worked with clients with eating disorders, heart problems and hypglycemia. He is a certified dietitian with 12 years of experience.",
	"Location": "Cupertino, CA",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p09",
	"image": "GroupImages/Wellness/Providers/Josh.jpg",
	"title": "Josh",
	"JobDesc": "Dietitian",
	"Rates": "$55/hr",
	"Ratings": 3,
	"shortDesc": "Jessie is a registered dietitian with a focus on healthy eating and weight management. He has 10 years experience in dealing with digestive disorders and irrtable bowel syndrome.",
	"Location": "Houston, TX",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p10",
	"image": "GroupImages/Wellness/Providers/Julio.jpg",
	"title": "Julio",
	"JobDesc": "Dietitian",
	"Rates": "$30/hr",
	"Ratings": 2,
	"shortDesc": "As a certified dietitian, Julio has worked with non-profit organisations to create awareness for healthy eating amongs schoolage children and teenagers.",
	"Location": "NewMarket, ON",
	"page": "www.google.com",
	"DetoxDiet": "N"
},
{
	"id": "p11",
	"image": "GroupImages/Wellness/Providers/Lily.jpg",
	"title": "Lily",
	"JobDesc": "Yoga Trainer",
	"Rates": "$50/hr",
	"Ratings": 5,
	"shortDesc": "Lily specializes in pre and post natal yoga and has been a trainer since 2009. Being a new mom herself, Lily has rediscovered the true essence of her practise.",
	"Location": "Pleasanton, CA",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p12",
	"image": "GroupImages/Wellness/Providers/Lucas.jpg",
	"title": "Lucas",
	"JobDesc": "Dietitian",
	"Rates": "$40/hr",
	"Ratings": 3,
	"shortDesc": "Lucas is a registered dietitian with a focus on diabetic diet. He has 13 years experience working with clients that have heart problems hypertension and food allergies.",
	"Location": "Logan, UT",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p13",
	"image": "GroupImages/Wellness/Providers/Naomi.jpg",
	"title": "Naomi",
	"JobDesc": "Nutritionist",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "As a nutritionist, Naomi has worked with children and has been a key presenter at various workshops and seminars. She specializes in infant/baby/toddler food preparation.",
	"Location": "Houston, TX",
	"page": "www.google.com",
	"DetoxDiet": "N"
},
{
	"id": "p14",
	"image": "GroupImages/Wellness/Providers/Roxanne.jpg",
	"title": "Roxanne",
	"JobDesc": "Dietitian",
	"Rates": "$70/hr",
	"Ratings": 4,
	"shortDesc": "Roxanne is a registered dietitian with a focus on diabetic diet. She has 15 years experience working with clients with heart problems and hypertension.",
	"Location": "San Mateo, CA",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p15",
	"image": "GroupImages/Wellness/Providers/Nate.jpg",
	"title": "Nate",
	"JobDesc": "Dietitian",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "As a certified dietitian, Nate has worked with seniors and non-profit organisations to create awareness for nutrition among older adults in late life.",
	"Location": "NewMarket, ON",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p16",
	"image": "GroupImages/Wellness/Providers/Nisha.jpg",
	"title": "Nisha",
	"JobDesc": "Naturopath",
	"Rates": "$30/hr",
	"Ratings": 3,
	"shortDesc": "Nisha's focuses to provide a caring space, thorough health assessments and individualized care. She artfully combines leading medical research with natural medicine. ",
	"Location": "Houston, TX",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p17",
	"image": "GroupImages/Wellness/Providers/Dahphne.jpg",
	"title": "Dahphne",
	"JobDesc": "Nutritionist",
	"Rates": "$30/hr",
	"Ratings": 3,
	"shortDesc": "Daphne focuses on body image issues and wholistic living. As a nutritionist, she has worked with school age children, teenagers and seniors.",
	"Location": "Cupertino, CA",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p18",
	"image": "GroupImages/Wellness/Providers/Olivia.jpg",
	"title": "Olivia",
	"JobDesc": "Naturopath",
	"Rates": "$50/hr",
	"Ratings": 5,
	"shortDesc": "Olivia is dedicated to understanding people, illness patterns and disease, allowing her and her patients to identify areas of the body that need support",
	"Location": "Houston, TX",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p19",
	"image": "GroupImages/Wellness/Providers/Rayaan.jpg",
	"title": "Rayaan",
	"JobDesc": "Yoga Trainer",
	"Rates": "$45/hr",
	"Ratings": 4,
	"shortDesc": "Rayaan has been practicing Ashtanga Yoag for over 30 years. She teaches clients how to take care of their health, body and mental wellness.",
	"Location": "NewMarket, ON",
	"page": "www.google.com",
	"DetoxDiet": "N"
},
{
	"id": "p20",
	"image": "GroupImages/Wellness/Providers/Rob.jpg",
	"title": "Rob",
	"JobDesc": "Naturopath",
	"Rates": "$30/hr",
	"Ratings": 2,
	"shortDesc": "The study of healing has been Rob's life long passion. He has a holistic approach towards treating patients has 20 years of experience in Naturopath,Homeopath and Chiropractor.",
	"Location": "Cupertino, CA",
	"page": "www.google.com",
	"DetoxDiet": "N"
},
{
	"id": "p21",
	"image": "GroupImages/Wellness/Providers/Steven.jpg",
	"title": "Steven",
	"JobDesc": "Naturopath",
	"Rates": "$60/hr",
	"Ratings": 4,
	"shortDesc": "Steven believes in stimulating and supporting the body's self-healing capacity. His focus areas are endocrine health, sports injuries, diabetes and heart conditions.",
	"Location": "Logan, UT",
	"page": "www.google.com",
	"DetoxDiet": "N"
},
{
	"id": "p22",
	"image": "GroupImages/Wellness/Providers/Tiffany.jpg",
	"title": "Tiffany",
	"JobDesc": "Naturopath",
	"Rates": "$35/hr",
	"Ratings": 3,
	"shortDesc": "Tiffany aims at optimal wellness and illness prevention through healthy diet & lifestyle. She uses a holistic approach by using herbal & chinese medicine and homeopathy.",
	"Location": "Pleasanton, CA",
	"page": "www.google.com",
	"DetoxDiet": "Y"
},
{
	"id": "p23",
	"image": "GroupImages/Wellness/Providers/Tim.jpg",
	"title": "Tim",
	"JobDesc": "Nutritionist",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "Tim is a certified nutritionist with 5 years of experiences. He has advised clients on nutrient supplements, food and nutrition trends. and dietary assessment.",
	"Location": "Pleasanton, CA",
	"page": "www.google.com",
	"DetoxDiet": "N"
},
{
	"id": "p24",
	"image": "GroupImages/Wellness/Providers/Trisha.jpg",
	"title": "Trisha",
	"JobDesc": "Yoga Trainer",
	"Rates": "$50/hr",
	"Ratings": 5,
	"shortDesc": "Trisha is a certified Jivamukti yoga teacher. Her classes focus on alignment, building strength and increasing flexibility.",
	"Location": "Cupertino, CA",
	"page": "www.google.com",
	"DetoxDiet": "Y"
}]