[{
	"id": "m01",
	"image": "GroupImages/Mindful/mindfulProviders/Ben.jpg",
	"title": "Ben",
	"JobDesc": "OB Specialist",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "Ben is an Organizational Behavior Specialist with 3 years of experience, specializing in corporate training and management.",
	"Location": "NewMarket, ON",
	"page": "",
	"goalSetting" : "Y"
},
{
	"id": "m02",
	"image": "GroupImages/Mindful/mindfulProviders/Elena.jpg",
	"title": "Elena",
	"JobDesc": "Psychologist",
	"Rates": "$40/hr",
	"Ratings": 5,
	"shortDesc": "Elena is a Psychologist with specialization in cognitive behavior threapy, and psychoanalysis. She has helped clients in community and clinical settings.",
	"Location": "Toronto, ON",
	"page": "www.google.com",
	"goalSetting" : "Y"
},
{
	"id": "m03",
	"image": "GroupImages/Mindful/mindfulProviders/Ethan.jpg",
	"title": "Ethan",
	"JobDesc": "Counsellor",
	"Rates": "$55/hr",
	"Ratings": 4,
	"shortDesc": "Ethan is certified counsellor with 5 years of experience. He has helped clients make choices within the framework of their contract.",
	"Location": "Santa Clara, CA",
	"page": "www.google.com",
	"goalSetting" : "Y"
},
{
	"id": "m04",
	"image": "GroupImages/Mindful/mindfulProviders/Jake.jpg",
	"title": "Matt",
	"JobDesc": "Case Manager",
	"Rates": "$30/hr",
	"Ratings": 4,
	"shortDesc": "Matt has a degree in Social Work and has worked as a case manager in rehabilitation centers for the past 12 yeras. Matt speicalized in motivation and cognition. ",
	"Location": "San Bruno, CA",
	"page": "www.google.com",
	"goalSetting" : "Y"
},
{
	"id": "m05",
	"image": "",
	"title": "",
	"JobDesc": "",
	"Rates": "$65/hr",
	"Ratings": 4,
	"shortDesc": "",
	"Location": "Bowling Green, OH",
	"page": "www.google.com",
	"goalSetting" : "N"
},
{
	"id": "m06",
	"image": "GroupImages/Mindful/mindfulProviders/LeAnn.jpg",
	"title": "Natasha",
	"JobDesc": "Yoga Trainer",
	"Rates": "$30/hr",
	"Ratings": 2,
	"shortDesc": "Natasha has a degree in Cognitive Psychology and has worked as a counsellor in community centers for the past 10 yeras. Natasha speicalized in behavior modification through coginitive therapy.",
	"Location": "Logan, UT",
	"page": "www.google.com",
	"goalSetting" : "Y"
},
{
	"id": "m07",
	"image": "",
	"title": "",
	"JobDesc": "",
	"Rates": "$45/hr",
	"Ratings": 4,
	"shortDesc": "",
	"Location": "Miami, FL",
	"page": "www.google.com",
	"goalSetting" : "N"
},
{
	"id": "m08",
	"image": "",
	"title": "",
	"JobDesc": "",
	"Rates": "$30/hr",
	"Ratings": 3,
	"shortDesc": "",
	"Location": "Cupertino, CA",
	"page": "www.google.com",
	"goalSetting" : "N"
},
{
	"id": "m09",
	"image": "",
	"title": "",
	"JobDesc": "",
	"Rates": "$55/hr",
	"Ratings": 3,
	"shortDesc": "",
	"Location": "Houston, TX",
	"page": "www.google.com",
	"goalSetting" : "N"
},
{
	"id": "m10",
	"image": "",
	"title": "",
	"JobDesc": "",
	"Rates": "$30/hr",
	"Ratings": 2,
	"shortDesc": "",
	"Location": "NewMarket, ON",
	"page": "www.google.com",
	"goalSetting" : "N"
}]