{	"providers":[{"id": "f15",
	"image": "GroupImages/Fitness/fitnessProviders/Catherine_sm.jpg",
	"title": "Catherine",
	"JobDesc": "Yoga Trainer",
	"Rates": [{"One hour, in-person": "$80"}, {"Half hour, in-person":"$40"}, {"One hour, online":"$30"}, {"Half hour, online":"$15"}],
	"Ratings": 4,
	"shortDesc": "Catherine is a certified fitness instructor with 8 years of experiences. She speicalizes in sports related injuries, rebahbilitation programs and post stroke and joint replacement rehab. Apart from sports activities, Catherine also consults on issues like weight loss, healthy eating and total body fitness.",
	"Location": "Newmarket, ON",
	"Latitude" : "44.0600",
	"Longitude" : "-79.4500",
	"Credentials":["Bachelors of Science in Sports Rehabilitation, University of Toronto, Canada", "Masters of Public Health, University of Washington, USA"],
	"Experience":"Catherine is a certified fitness instructor with 8 years of experiences. She speicalizes in sports related injuries, rebahbilitation programs and post stroke and joint replacement rehab. ",
	"Details":[{"Languages Spoken":"English, Mandarin"}, {"Accepted Insurance":"Aetna, Blue Cross Blue Sheild"}, {"Specialities":"Meal Planning, Weight Loss"}],
	"Appointment":"Available",
	"pageLink": "Mixed_Interval_30",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f19",
	"image": "GroupImages/Fitness/fitnessProviders/Jackie_sm.jpg",
	"title": "Jackie",
	"JobDesc": "Health Trainer",
	"Rates": [{"One hour, in-person": "$60"}, {"Half hour, in-person":"$30"}, {"One hour, online":"$45"}, {"Half hour, online":"$30"}],
	"Ratings": 4,
	"shortDesc": "Jackie has a real passion for fitness and an understanding for life changing effects of a successful exercise and nutritional program. Train with Jackie to achieve all your health and wellness goals.",
	"Location": "Newmarket, ON",
	"Latitude" : "44.0600",
	"Longitude" : "-79.4500",
	"Credentials":["Bachelors of Science in Sports Rehabilitation, University of Toronto, Canada", "Masters of Public Health, University of Washington, USA"],
	"Experience":"Jackie has a real passion for fitness and an understanding for life changing effects of a successful exercise and nutritional program. Train with Jackie to achieve all your health and wellness goals.",
	"Details":[{"Languages Spoken":"English, Mandarin"}, {"Accepted Insurance":"Aetna, Blue Cross Blue Sheild"}, {"Specialities":"Meal Planning, Weight Loss"}],
	"Appointment":"Available",
	"pageLink": "High_Intensity_Aerobics",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f16",
	"image": "GroupImages/Fitness/fitnessProviders/Lex_sm.jpg",
	"title": "Lex",
	"JobDesc": "Fitness Expert",
	"Rates": [{"One hour, in-person": "$40"}, {"Half hour, in-person":"$20"}, {"One hour, online":"$30"}, {"Half hour, online":"$15"}],
	"Ratings": 3,
	"shortDesc": "Lex is a fitness expert with over 8 years of experience. He is a friendly and dedicated personal trainer who helps people with their health and fitness goals.",
	"Location": "Houston, TX",
	"Latitude" : "29.760427",
	"Longitude" : "-95.369803",
	"Credentials":["Bachelors of Science in Kinesiology, University of Austin, Texas"],
	"Experience":"",
	"Details":[{"Languages Spoken":"English, Spanish"}, {"Accepted Insurance":"Kaiser Permanente"}, {"Specialities":"Cross Training, Muscle Building, Professional Wrestling"}],
	"Appointment":"Available",
	"pageLink": "Mixed_Interval_30",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f04",
	"image": "GroupImages/Fitness/fitnessProviders/Matt_sm.jpg",
	"title": "Matt",
	"JobDesc": "Cardio Trainer",
	"Rates": [{"One hour, in-person": "$40"}, {"Half hour, in-person":"$20"}, {"One hour, online":"$30"}, {"Half hour, online":"$15"}],
	"Ratings": 5,
	"shortDesc": "Matt is a trainer with 5 years of experience. He offers customized meal plans, training sessions, and lifestyle maintance programs.",
	"Location": "San Bruno, CA",
	"Latitude" : "37.630490",
	"Longitude" : "-122.411084",
	"Credentials":["Certified Cardio Trainer, University of California, Davis"],
	"Experience":"4 years",
	"Details":[{"Languages Spoken":"English, Spanish"}, {"Accepted Insurance":"Anthem California"}, {"Specialities":"Cardio Training, Core Strengthening"}],
	"Appointment":"Available",
	"pageLink": "Mixed_Interval_30",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f06",
	"image": "GroupImages/Fitness/fitnessProviders/Natasha_sm.jpg",
	"title": "Natasha",
	"JobDesc": "Yoga Trainer",
	"Rates": [{"One hour, in-person": "$50"}, {"Half hour, in-person":"$25"}, {"One hour, online":"$30"}, {"Half hour, online":"$15"}],
	"Ratings": 2,
	"shortDesc": "Natasha is a seasoned personal Trainer. Her portfolio ranges from pre and post natal clients, athletes, weight losers and 10 years of experience a group exercise instructor.",
	"Location": "Logan UT",
	"Latitude" : "41.736980",
	"Longitude" : "-111.833836",
	"Credentials":["Certified Hatha Yoga Trainer, Institute of Hatha Yoga"],
	"Experience":"10 years",
	"Details":[{"Languages Spoken":"English"}, {"Accepted Insurance":""}, {"Specialities":"Pre and post natal yoga, Weight Loss, Pilates"}],
	"Appointment":"Available",
	"pageLink": "Mixed_Interval_30",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f18",
	"image": "GroupImages/Fitness/fitnessProviders/Tom_sm.jpg",
	"title": "Tom",
	"JobDesc": "Trainer",
	"Rates": [{"One hour, in-person": "$50"}, {"Half hour, in-person":"$25"}, {"One hour, online":"$30"}, {"Half hour, online":"$15"}],
	"Ratings": 3,
	"shortDesc": "Tom has worked as a fitness trainer for 15 years and motivates his clients providing coaching and knowledge to achieve their goals.",
	"Location": "Houston, TX",
	"Latitude" : "29.760427",
	"Longitude" : "-95.369803",
	"Credentials":["Bachelors of Science, Physiology, Texas State University"],
	"Experience":"5 years",
	"Details":[{"Languages Spoken":"English"}, {"Accepted Insurance":"Great Life West"}, {"Specialities":"Marathon training, Core Strengthening, Muscle Building"}],
	"Appointment":"Available",
	"pageLink": "",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f03",
	"image": "GroupImages/Fitness/fitnessProviders/Jeremy_sm.jpg",
	"title": "Jeremy",
	"JobDesc": "Trainer",
	"Rates": [{"One hour, in-person": "$80"}, {"Half hour, in-person":"$40"}, {"One hour, online":"$55"}, {"Half hour, online":"$30"}],
	"Ratings": 4,
	"shortDesc": "Jeremy is a fitness trainer since the year 2000 and has helped his clients with their weight loss, muscle gain, and sports performance goals.",
	"Location": "Santa Clara, CA",
	"Latitude" : "37.354108",
	"Longitude" : "-121.955236",
	"Credentials":["Bachelors of Science in Sports Rehabilitation, University of Southern California, California"],
	"Experience":"Jeremy is a fitness trainer since the year 2000 and has helped his clients with their weight loss, muscle gain, and sports performance goals.",
	"Details":[{"Languages Spoken":"English, Spanish"}, {"Accepted Insurance":"Anthem, Kaiser Permanente"}, {"Specialities":"Cardio, Weight Loss"}],
	"Appointment":"Available",
	"pageLink": "Mixed_Interval_30",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f01",
	"image": "GroupImages/Fitness/fitnessProviders/Nash_sm.jpg",
	"title": "Nash",
	"JobDesc": "Fitness Coach",
	"Rates": [{"One hour, in-person": "$60"}, {"Half hour, in-person":"$40"}, {"One hour, online":"$30"}, {"Half hour, online":"$20"}],
	"Ratings": 4,
	"shortDesc": "Nash is a certified cardio trainer with 5 years of experience. He has worked with numerous clients on issues like weight loss, heart fitness, and muscle toning for different ages.",
	"Location": "NewMarket, ON",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelors of Arts in Philosophy, University of New Mexico, New Mexico"],
	"Experience":"Nash is a certified cardio trainer with 5 years of experience. He has worked with numerous clients on issues like weight loss, heart fitness, and muscle toning for different ages.",
	"Details":[{"Languages Spoken":"English, Spanish"}, {"Accepted Insurance":"Anthem, Kaiser Permanente"}, {"Specialities":"Cardio, Yoga, Marathon running."}],
	"Appointment":"Available",
	"pageLink": "Low_Impact_Cardio",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f02",
	"image": "GroupImages/Fitness/fitnessProviders/Evan.jpg",
	"title": "Evan",
	"JobDesc": "Interval Trainer",
	"Rates": [{"One hour, in-person": "$60"}, {"Half hour, in-person":"$30"}, {"One hour, online":"$40"}, {"Half hour, online":"$20"}],
	"Ratings": 5,
	"shortDesc": "Evan is a Cardio Trainer with 12 years of experience. His specialization is Interval training that helps to keep his clients in top shape. Evan is also a yoga enthusiast with a specialization in Hatha Yoga.",
	"Location": "Toronto, ON",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelors of Arts in Psychology, University of Arizona, Arizona"],
	"Experience":"Evan is a Cardio Trainer with 12 years of experience. His specialization is Interval training that helps to keep his clients in top shape. Evan is also a yoga enthusiast with a specialization in Hatha Yoga.",
	"Details":[{"Languages Spoken":"English, Spanish"}, {"Accepted Insurance":"Sun Life, Cigna"}, {"Specialities":"Ashtanga Yoga, Iyengar Yoga, Interval training, Weight loss"}],
	"Appointment":"Available",
	"pageLink": "Interval_Training_for_Beginners",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f05",
	"image": "GroupImages/Fitness/fitnessProviders/Josh.jpg",
	"title": "Josh",
	"JobDesc": "Personal Trainer",
	"Rates": [{"One hour, in-person": "$100"}, {"Half hour, in-person":"$50"}, {"One hour, online":"$65"}, {"Half hour, online":"$40"}],
	"Ratings": 4,
	"shortDesc": "Josh has worked with a variety of clients as a personal trainer.  Over the past 3 years he has helped his clients in aerobic, cicuit and strength training.",
	"Location": "Bowling Green, OH",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelor's of Science in Chemistry, University of Arkansas, Arkansas"],
	"Experience":"Josh has worked with a variety of clients as a personal trainer.  Over the past 3 years he has helped his clients in aerobic, cicuit and strength training.",
	"Details":[{"Languages Spoken":"English, Russian"}, {"Accepted Insurance":"Humana , WellPoint"}, {"Specialities":"KettleBells, Interval training, Circuit training"}],
	"Appointment":"Available",
	"pageLink": "Cardio_Basics",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f07",
	"image": "GroupImages/Fitness/fitnessProviders/Nate.jpg",
	"title": "Nate",
	"JobDesc": "Cardio Trainer",
	"Rates": [{"One hour, in-person": "$60"}, {"Half hour, in-person":"$30"}, {"One hour, online":"$45"}, {"Half hour, online":"$20"}],
	"Ratings": 4,
	"shortDesc": "Nate has more than 5 years of experience as a cardio trainer. He focuses on edurance or aerobic training for heart health and strength training for muscle building.",
	"Location": "Miami, FL",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelor's of Science in Political Science, Delaware State University, Delaware"],
	"Experience":"Nate has more than 5 years of experience as a cardio trainer. He focuses on edurance or aerobic training for heart health and strength training for muscle building.",
	"Details":[{"Languages Spoken":"English, German, Spanish"}, {"Accepted Insurance":"Humana , WellPoint"}, {"Specialities":"Hatha Yoga, Kundalini Yoga, Outdoor fitness"}],
	"Appointment":"Available",
	"pageLink": "Cardio_for_Weight_Loss",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f08",
	"image": "GroupImages/Fitness/fitnessProviders/Lily.jpg",
	"title": "Lily",
	"JobDesc": "Yoga Trainer",
	"Rates": [{"One hour, in-person": "$50"}, {"Half hour, in-person":"$25"}, {"One hour, online":"$30"}, {"Half hour, online":"$15"}],
	"Ratings": 4,
	"shortDesc": "Lily is a trained yoga professional that uses yoga for maintaining healthy health and weight loss.",
	"Location": "Cupertino, CA",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelors of Science in Health and Wellness, University of California, Irvine, Californa"],
	"Experience":"Lily is a trained yoga professional that uses yoga for maintaining healthy health and weight loss.",
	"Details":[{"Languages Spoken":"English, Taglog"}, {"Accepted Insurance":"Blue Cross Blue Sheild, UnitedHealth"}, {"Specialities":"Pregnancy Yoga, Hot Yoga, Kickboxing, Zumba dancing, Balancing on the ball"}],
	"Appointment":"Available",
	"pageLink": "Cardio_for_Weight_Loss",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f09",
	"image": "GroupImages/Fitness/fitnessProviders/Tim.jpg",
	"title": "Tim",
	"JobDesc": "Health Coach",
	"Rates": [{"One hour, in-person": "$55"}, {"Half hour, in-person":"$30"}, {"One hour, online":"$55"}, {"Half hour, online":"30"}],
	"Ratings": 3,
	"shortDesc": "Tim is a high energy coach that keeps his clients motivated with new fitness techniques and ideas. He specializes in sculpting, core training, and kickboxing.",
	"Location": "Houston, TX",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelors of Science in Health Sciences, East Georgia State College, Georgia"],
	"Experience":"Tim is a high energy coach that keeps his clients motivated with new fitness techniques and ideas. He specializes in sculpting, core training, and kickboxing.",
	"Details":[{"Languages Spoken":"English, Italian, Mandarin"}, {"Accepted Insurance":"Wellcare, UnitedHealth"}, {"Specialities":"Restorative Yoga, Yoga for athletic recovery, Continuous training for weight loss"}],
	"Appointment":"Available",
	"pageLink": "Burn_Fat",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f10",
	"image": "GroupImages/Fitness/fitnessProviders/Steven.jpg",
	"title": "Steven",
	"JobDesc": "Trainer",
	"Rates": [{"One hour, in-person": "$40"}, {"Half hour, in-person":"$25"}, {"One hour, online":"$30"}, {"Half hour, online":"20"}],
	"Ratings": 2,
	"shortDesc": "Steven helps young professionals and executives create systems to accelerate their weight loss goals. He develops individualized weight loss programs based on client needs.",
	"Location": "NewMarket, ON",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelors of Arts in "],
	"Experience":"Steven helps young professionals and executives create systems to accelerate their weight loss goals. He develops individualized weight loss programs based on client needs.",
	"Details":[{"Languages Spoken":"English, Portugese"}, {"Accepted Insurance":"HealthPartners, Kaiser Permanente"}, {"Specialities":"Cardio for weight loss, Intensity training, muscle toning"}],
	"Appointment":"Available",
	"pageLink": "Interval_Training_for_Beginners",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f11",
	"image": "GroupImages/Fitness/fitnessProviders/Roxanne.jpg",
	"title": "Roxanne",
	"JobDesc": "Trainer",
	"Rates": [{"One hour, in-person": "$50"}, {"Half hour, in-person":"$30"}, {"One hour, online":"$50"}, {"Half hour, online":"30"}],
	"Ratings":5 ,
	"shortDesc": "Being an active and athletic person all her life, choosing a career as a fitness trainer was easy for Roxanne. She works with clients of all ages, developing personalized sessions and delivering them.",
	"Location": "Pleasanton, CA",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelor of Science in Physiotherapy, University of California, Davis"],
	"Experience":"Being an active and athletic person all her life, choosing a career as a fitness trainer was easy for Roxanne. She works with clients of all ages, developing personalized sessions and delivering them.",
	"Details":[{"Languages Spoken":"English, Tagalog"}, {"Accepted Insurance":"Cigna, Fortis, Health Net"}, {"Specialities":"Sports Injuries rehabilitation, Cardio, Kick boxing"}],
	"Appointment":"Available",
	"pageLink": "At_Home_Cardio",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f12",
	"image": "GroupImages/Fitness/fitnessProviders/Rob.jpg",
	"title": "Rob",
	"JobDesc": "Trainer",
	"Rates": [{"One hour, in-person": "$60"}, {"Half hour, in-person":"$30"}, {"One hour, online":"$40"}, {"Half hour, online":"25"}],
	"Ratings": 3,
	"shortDesc": "Rob believes that for the body to work optimally, it must be in  balance. Following this approach, Rob focuses on cadrio, strengthening, flexibility, core and balancing exercises.",
	"Location": "Logan, UT",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Masters of Arts, Social Studies, University of Utah, UT"],
	"Experience":"Rob believes that for the body to work optimally, it must be in  balance. Following this approach, Rob focuses on cadrio, strengthening, flexibility, core and balancing exercises.",
	"Details":[{"Languages Spoken":"English, Spanish"}, {"Accepted Insurance":"Humana, Blue Cross"}, {"Specialities":"Core strengthening, Cross training, Endurance building"}],
	"Appointment":"Available",
	"pageLink": "At_Home_Cardio",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f13",
	"image": "GroupImages/Fitness/fitnessProviders/Rayaan.jpg",
	"title": "Rayaan",
	"JobDesc": "Cardio Expert",
	"Rates": [{"One hour, in-person": "$40"}, {"Half hour, in-person":"$20"}, {"One hour, online":"$30"}, {"Half hour, online":"15"}],
	"Ratings": 4,
	"shortDesc": "Rayaan has an extensive training in Stott Pilates, Matwork and equipment, kettlebell and kickboxing. She has worked with rehab clients and believes in a wholistic approach towards wellbeing.",
	"Location": "Houston, TX",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelor's of Science, Health Sciences, University of Illinois, Illinois"],
	"Experience":"Rayaan has an extensive training in Stott Pilates, Matwork and equipment, kettlebell and kickboxing. She has worked with rehab clients and believes in a wholistic approach towards wellbeing.",
	"Details":[{"Languages Spoken":"English, Chinese, German"}, {"Accepted Insurance":"LifeWise, UnitedHealth Group, State Farm"}, {"Specialities":"Cardio training, Weight lifting, Resistance band training"}],
	"Appointment":"Available",
	"pageLink": "At_Home_Cardio",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f14",
	"image": "GroupImages/Fitness/fitnessProviders/Olivia.jpg",
	"title": "Olivia",
	"JobDesc": "Health Coach",
	"Rates": [{"One hour, in-person": "$70"}, {"Half hour, in-person":"$35"}, {"One hour, online":"$70"}, {"Half hour, online":"35"}],
	"Ratings": 4,
	"shortDesc": "Olivia specializes in one-on-one coaching, focusing on personal goal setting. She has 7 years of experience as a health coach with experience in HIIT, cardio training, weight loss and core training.",
	"Location": "San Mateo, CA",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Masters in Public Health, Loma Linda University, CA"],
	"Experience":"Olivia specializes in one-on-one coaching, focusing on personal goal setting. She has 7 years of experience as a health coach with experience in HIIT, cardio training, weight loss and core training.",
	"Details":[{"Languages Spoken":"English, Spanish"}, {"Accepted Insurance":"WellPoint, WellCare, Medica"}, {"Specialities":"High intensity interval training, Endurance building, Aerobics"}],
	"Appointment":"Available",
	"pageLink": "HIIT",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
}












,
{	"id": "f17",
	"image": "GroupImages/Fitness/fitnessProviders/Julio.jpg",
	"title": "Julio",
	"JobDesc": "Health Coach",
	"Rates": [{"One hour, in-person": "$50"}, {"Half hour, in-person":"$30"}, {"One hour, online":"$30"}, {"Half hour, online":"20"}],
	"Ratings": 3,
	"shortDesc": "Juilio believes in making people the masters of their own health. He coaches clients about their strengths and has 10-plus years of experience in endurance sports.",
	"Location": "Cupertino, CA",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Certified Yoga Teacher, Yogatree, Canada"],
	"Experience":"Juilio believes in making people the masters of their own health. He coaches clients about their strengths and has 10-plus years of experience in endurance sports.",
	"Details":[{"Languages Spoken":"English, French, Japanese"}, {"Accepted Insurance":"EmblemHealth, Molina Healthcare"}, {"Specialities":"Restorative Yoga, High interval workouts, Vinyasa Yoga, Cardio, Endurance"}],
	"Appointment":"Available",
	"pageLink": "HIIT",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f20",
	"image": "GroupImages/Fitness/fitnessProviders/Naomi.jpg",
	"title": "Naomi",
	"JobDesc": "Health Coach",
	"Rates": [{"One hour, in-person": "$40"}, {"Half hour, in-person":"$20"}, {"One hour, online":"$30"}, {"Half hour, online":"15"}],
	"Ratings": 2,
	"shortDesc": "Naomi has trained with multiple level clients, from beginners to athletes. She enjoys building a personal rapport with her clients and working at a pace that suits her clients.",
	"Location": "Cupertino, CA",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Certified ACE Trainer, American Council on Exercise (ACE) Institute"],
	"Experience":"Naomi has trained with multiple level clients, from beginners to athletes. She enjoys building a personal rapport with her clients and working at a pace that suits her clients.",
	"Details":[{"Languages Spoken":"English, Italian"}, {"Accepted Insurance":"Aetna, Conseco"}, {"Specialities":"High intensity aerobics, Total body workout, Posture maintenance"}],
	"Appointment":"Available",
	"pageLink": "High_Intensity_Aerobics",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f21",
	"image": "GroupImages/Fitness/fitnessProviders/JoAnn.jpg",
	"title": "JoAnn",
	"JobDesc": "Health Coach",
	"Rates": [{"One hour, in-person": "$60"}, {"Half hour, in-person":"$30"}, {"One hour, online":"$60"}, {"Half hour, online":"30"}],
	"Ratings": 4,
	"shortDesc": "JoAnn is a certified ACE personal trainer. She specializes in pre and post natal care, weight loss, injury rehabilitation, and muscle toning.",
	"Location": "Logan, UT",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Certified ACE personal trainer, ACE Institute"],
	"Experience":"JoAnn is a certified ACE personal trainer. She specializes in pre and post natal care, weight loss, injury rehabilitation, and muscle toning.",
	"Details":[{"Languages Spoken":"English, Portugese, Spanish"}, {"Accepted Insurance":"Amerigroup, Fortis"}, {"Specialities":"Cardio and endurance training, Total body workouts, on-the-ball training"}],
	"Appointment":"Available",
	"pageLink": "Cardio_Basics",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f22",
	"image": "GroupImages/Fitness/fitnessProviders/Jesse.jpg",
	"title": "Jesse",
	"JobDesc": "Trainer",
	"Rates": [{"One hour, in-person": "$50"}, {"Half hour, in-person":"$25"}, {"One hour, online":"$35"}, {"Half hour, online":"20"}],
	"Ratings": 3,
	"shortDesc": "Jesse is a certified personal trainer who has spent last 15 years learning about the importance of fitness and training. He is a dedicated weight trainer who helps clients attain healthy body weight.",
	"Location": "Pleasanton, CA",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelors of Science, Kinesiology, Ball State University, Indiana"],
	"Experience":"Jesse is a certified personal trainer who has spent last 15 years learning about the importance of fitness and training. He is a dedicated weight trainer who helps clients attain healthy body weight.",
	"Details":[{"Languages Spoken":"English, Russian, Polish"}, {"Accepted Insurance":"Highmark, Aetna, HealthSpring"}, {"Specialities":"Cardio, Strength training, Muscle building"}],
	"Appointment":"Available",
	"pageLink": "Low_Impact_Cardio",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f23",
	"image": "GroupImages/Fitness/fitnessProviders/Dahphne.jpg",
	"title": "Dahphne",
	"JobDesc": "Fitness Expert",
	"Rates": [{"One hour, in-person": "$30"}, {"Half hour, in-person":"$20"}, {"One hour, online":"$30"}, {"Half hour, online":"20"}],
	"Ratings": 4,
	"shortDesc": "Dahpne believes that true fitness is a holistic model and offers training in muscle toning, weight management and personal wellness.",
	"Location": "Pleasanton, CA",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Bachelor's in Biology,University of Waterloo, ON"],
	"Experience":"Dahpne believes that true fitness is a holistic model and offers training in muscle toning, weight management and personal wellness.",
	"Details":[{"Languages Spoken":"English, French"}, {"Accepted Insurance":"Blue Cross, Blue Shield"}, {"Specialities":"Exercise for older adults, Cardio, Strength training"}],
	"Appointment":"Available",
	"pageLink": "Low_Impact_Cardio",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
},
{	"id": "f24",
	"image": "GroupImages/Fitness/fitnessProviders/Trisha.jpg",
	"title": "Trisha",
	"JobDesc": "Yoga Trainer",
	"Rates": [{"One hour, in-person": "$100"}, {"Half hour, in-person":"$50"}, {"One hour, online":"$50"}, {"Half hour, online":"40"}],
	"Ratings": 1,
	"shortDesc": "Trisha is a certified Jivamukti yoga teacher. Her classes focus on alignment, building strength and increasing flexibility.",
	"Location": "Cupertino, CA",
	"Latitude" : "",
	"Longitude" : "",
	"Credentials":["Certified Yoga trainers, Bikram Yoga Institute"],
	"Experience":"Trisha is a certified Jivamukti yoga teacher. Her classes focus on alignment, building strength and increasing flexibility.",
	"Details":[{"Languages Spoken":"English, "}, {"Accepted Insurance":"HealthPoint, Aetna"}, {"Specialities":"Pregnancy yoga, Outdoor sports, Injury Rehab"}],
	"Appointment":"Available",
	"pageLink": "Outdoor_Workouts",
	"Videos":[{"GroupImages/Fitness/Cardio/CardioStep.jpg":"Burning fat with cardio"}, {"GroupImages/Fitness/Strength/strengthDumbells.jpg": "Dumbelss for better shoulders"}, {"GroupImages/Fitness/Strength/strengthWt.jpg":"Doing weights the right way"}, {"GroupImages/Fitness/moreWorkouts/mwKickBox.jpg":"Yoga for lower back pain"}],
	"Article":[{"FitnessPages/GoodToKnow/CardioFatBurn.jpg":"Burn Fat with Cardio workouts"}, {"FitnessPages/GoodToKnow/CardioCycle.jpg":"Dos and don'ts of working out in the outdoors"},{"FitnessPages/GoodToKnow/CardioIntense.jpg":"How to build core strength"}],
	"Reviews":[{"userPic":"FitnessPages/Users/Nancy.jpg", "userName":"Nancy", "rateNum":"4", "rateDesc":"Alexia had a solid understanding of weight loss issue. Her feedback was timely, appropiate and insightful. I would highly recommend her services."}, {"userPic":"FitnessPages/Users/Emily.jpg", "userName":"Emily", "rateNum":"5", "rateDesc":"She is so helpful and made me feel 100% better!! Thank you ! She is also knowledge about all medications, very professional, and very kind. You can tell she really cares about you and your well being."}, {"userPic":"FitnessPages/Users/Steve.jpg", "userName":"Steve", "rateNum":"4", "rateDesc":"I had the pleasure of meeting with Alexa to discuss my diet and ways to help improve it. I found her to be knowledgeable and I appreciated the way she knew the right questions to ask to determine what I was doing wrong. She provided great pointers and goals for the future that I should initiate. All in all a worthwhile experience."}]
}



























]}








